version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  usermanager-node: #name of the express app service
    build: "." # specify the directory of the Dockerfile for express app
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database # link this service to the mongodb service

  database: # name of the mongodb service
    image: mongo # specify image to build container from. This image is available on dockerhub
    ports:
      - "27018:27017" # specify port forwarding
      